//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateDBConnectionLibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\50statesDB.mdf;Integrat" +
            "ed Security=True;Connect Timeout=30;User Instance=True")]
        public string _50statesDBConnectionString {
            get {
                return ((string)(this["_50statesDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\StatesDataBab" +
            "se.mdf;Integrated Security=True;Connect Timeout=30")]
        public string StatesDataBabseConnectionString {
            get {
                return ((string)(this["StatesDataBabseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"C:\\Users\\gong_\\Desktop\\2024SP - CPT 20" +
            "6 - A80S - Adv Event-Driven Program\\gvang_CPT_206_StateApp2\\gvang_CPT_206_StateA" +
            "pp2\\50statesDB.mdf\";Integrated Security=True;Connect Timeout=30;User Instance=Tr" +
            "ue")]
        public string _50statesDBConnectionString1 {
            get {
                return ((string)(this["_50statesDBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"C:\\Users\\gong_\\Desktop\\2024SP - CPT 20" +
            "6 - A80S - Adv Event-Driven Program\\DATA\\50statesDB.mdf\";Integrated Security=Tru" +
            "e;Connect Timeout=30;User Instance=True")]
        public string _50statesDBConnectionString2 {
            get {
                return ((string)(this["_50statesDBConnectionString2"]));
            }
        }
    }
}
